
module.exports = Object.freeze({
    MODAL_BODY_TYPES : {
        BARANG_ADD_NEW : "BARANG_ADD_NEW",
        CONFIRMATION : "CONFIRMATION",
        DEFAULT : "",
        KATEGORI_ADD_NEW : "KATEGORI_ADD_NEW",
        KATEGORI_EDIT : "KATEGORI_EDIT",
        TRANSAKSI_ADD_NEW : "TRANSAKSI_ADD_NEW",
    },

    RIGHT_DRAWER_TYPES : {
        NOTIFICATION : "NOTIFICATION",
        CALENDAR_EVENTS : "CALENDAR_EVENTS",
    },

    CONFIRMATION_MODAL_CLOSE_TYPES : {
        KATEGORI_DELETE : "KATEGORI_DELETE",
    },
});
